# Proper Stock-Flow Consistent Kalman Filter Configuration
# Complete implementation with all constraints properly enforced

sfc:
  # Core SFC enforcement settings
  enforce_sfc: true                    # Master switch for SFC constraints
  enforce_market_clearing: true        # Enforce assets = liabilities by instrument
  enforce_bilateral: true              # Enforce bilateral aggregation
  include_revaluations: true          # Model FR/FV as explicit states
  
  # Variance ratios for different state types
  error_variance_ratio: 0.01          # Base measurement error
  reval_variance_ratio: 0.1           # Revaluation state variance (FR/FV more volatile)
  bilateral_variance_ratio: 0.05      # Bilateral state variance
  
  # Data processing
  normalize_data: true                 # Normalize before filtering
  transformation: 'square'             # Hierarchical transformation type
  
  # Performance settings
  max_series: 500                     # Maximum series to use
  use_sparse: true                    # Use sparse matrices (essential for large systems)
  
  # Validation
  validation_tolerance: 1e-6          # Tolerance for constraint satisfaction
  create_visualizations: true         # Generate diagnostic plots

  # Paths
  base_dir: ./data/fed_data
  cache_dir: ./data/cache
  output_dir: ./outputs
  date: 1965-12-31

  instrument_map: mappings/instrument_map.json
  flow_map: mappings/flow_map_expanded.json

  # mode-specific
  fwtw: data/fwtw_levels.csv
  graph_spec: graphs/graph_adjacency_spec.json
  instrument_group_map: mappings/instrument_group_map.json
  graph_spec_refined: graphs/graph_adjacency_spec_refined.json

# Run mode configurations
run_modes:
  # Quick test - minimal data, basic constraints
  test:
    max_series: 50
    enforce_market_clearing: false
    enforce_bilateral: false
    include_revaluations: true
    create_visualizations: false
    
  # Development - moderate data, core constraints
  development:
    max_series: 200
    enforce_sfc: true
    enforce_market_clearing: true
    enforce_bilateral: false           # Skip for speed
    include_revaluations: true
    
  # Production - full constraints, reasonable data
  production:
    max_series: 500
    enforce_sfc: true
    enforce_market_clearing: true
    enforce_bilateral: true
    include_revaluations: true
    
  # Full - all sectors/instruments (memory intensive)
  full:
    max_series: 2000
    enforce_sfc: true
    enforce_market_clearing: true
    enforce_bilateral: true
    include_revaluations: true
    use_sparse: true                  # Essential at this scale

# Series selection priorities
priorities:
  # Sectors to prioritize (most important first)
  sectors:
    - '10'  # Nonfinancial corporate business
    - '15'  # Households and nonprofit organizations
    - '26'  # Rest of the world
    - '31'  # Federal government
    - '70'  # Private depository institutions
    - '89'  # All sectors (totals)
    - '90'  # Instrument discrepancies
    
  # Instruments to prioritize
  instruments:
    - '30641'  # Corporate equities
    - '31305'  # Treasury securities
    - '40005'  # Consumer credit
    - '71305'  # Municipal securities
    - '40305'  # Bank loans

# Constraint configuration
constraints:
  # Stock-flow identity settings
  stock_flow:
    enforce_exact: true               # Exact vs approximate
    include_lags: true                # Handle FL[t-1] properly
    tolerance: 1e-10                  # Numerical tolerance
    
  # Market clearing settings
  market_clearing:
    by_instrument: true               # Clear each instrument separately
    by_date: true                     # Clear at each time period
    allow_discrepancy: 0.001          # Small tolerance for data issues
    
  # Bilateral settings
  bilateral:
    require_coverage: 0.8             # Minimum coverage to enforce
    aggregate_method: 'sum'           # How to aggregate positions
    
  # Formula settings
  formulas:
    parse_all: true                   # Parse all available formulas
    enforce_dependencies: true        # Enforce formula dependencies
    max_lag: 4                       # Maximum lag to consider

# Numerical settings
numerics:
  # Projection settings
  projection:
    tolerance: 1e-10
    max_iterations: 10
    use_joseph_form: true            # Numerical stability for covariance
    regularization: 1e-12             # Small regularization for singularity
    
  # Sparse matrix settings
  sparse:
    format: 'csr'                     # Compressed sparse row
    threshold: 0.1                    # Sparsity threshold
    use_iterative_solvers: true      # For very large systems
    
  # Initialization
  initialization:
    method: 'diffuse'                 # Initialization method
    variance_scale: 1000              # Scale for initial variance

# Output configuration
output:
  # What to save
  save_states: true                   # Save filtered/smoothed states
  save_covariances: false            # Save covariance matrices (large!)
  save_diagnostics: true             # Save constraint diagnostics
  save_shocks: true                  # Save shock decomposition
  
  # Formats
  state_format: 'npy'                # NumPy binary format
  data_format: 'parquet'             # Parquet for DataFrames
  compression: 'snappy'              # Compression type
  
  # Diagnostics to compute
  diagnostics:
    constraint_violations: true       # Track violations over time
    shock_contributions: true         # Decompose by shock source
    state_evolution: true             # Track state dynamics
    
# Logging configuration  
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: null                         # Log file (null = console only)
